<#
    Regenerates site/downloads.json from the binaries in dist-release.

    Run this after every release build, before deploying. Publishing a SHA-256
    that does not match the file people actually download is worse than
    publishing none at all, so this reads the real bytes rather than trusting
    anything written by hand.

    Usage:
        powershell -ExecutionPolicy Bypass -File site\update-downloads.ps1
#>

$ErrorActionPreference = 'Stop'

$root    = Split-Path -Parent $PSScriptRoot
$release = Join-Path $root 'dist-release'
$out     = Join-Path $PSScriptRoot 'downloads.json'

# Version comes from package.json so there is one source of truth for it.
$version = (Get-Content (Join-Path $root 'package.json') -Raw | ConvertFrom-Json).version

# The installer's filename is produced by the Tauri bundler from the version in
# tauri.conf.json, not the one in package.json. Reading it from anywhere else
# means a version drift makes this script look for a file that was never built.
$tauriVersion = (Get-Content (Join-Path $root 'src-tauri\tauri.conf.json') -Raw |
    ConvertFrom-Json).version
if ($tauriVersion -ne $version) {
    throw "Version mismatch: package.json says $version, tauri.conf.json says " +
          "$tauriVersion. Reconcile them before publishing, or the download " +
          "link and the built installer will disagree."
}

$installerName = "AllInsight_${tauriVersion}_x64-setup.exe"
$portableName  = 'AllInsight.exe'

function Get-Entry {
    param([string]$Name)

    # Deliberately fatal. The earlier version returned nulls here, which wrote a
    # downloads.json with no hashes over a previously correct one and still
    # exited 0 -- so running this before a build quietly destroyed good data.
    $path = Join-Path $release $Name
    if (-not (Test-Path $path)) {
        throw "$Name not found in $release. Run BUILD_WINDOWS.bat first; " +
              "downloads.json has been left untouched."
    }

    $item = Get-Item $path
    [ordered]@{
        file   = $Name
        bytes  = $item.Length
        sha256 = (Get-FileHash $path -Algorithm SHA256).Hash.ToLower()
    }
}

$json = [ordered]@{
    _note     = 'Generated by site/update-downloads.ps1. Do not edit by hand.'
    version   = $version
    licence   = 'MIT'
    installer = Get-Entry $installerName
    portable  = Get-Entry $portableName
}

# Written without a byte order mark. Windows PowerShell's -Encoding utf8 emits
# one, and a BOM at the head of a .json file is a decoding hazard for anything
# that reads the bytes rather than running them through a UTF-8 decoder.
[System.IO.File]::WriteAllText(
    $out,
    ($json | ConvertTo-Json -Depth 4),
    (New-Object System.Text.UTF8Encoding $false)
)

Write-Host "Wrote $out" -ForegroundColor Green
Write-Host "  installer : $($json.installer.sha256)"
Write-Host "  portable  : $($json.portable.sha256)"
Write-Host ''
Write-Host 'Copy both .exe files to the VM at /var/www/allinsight/downloads/ so the'
Write-Host 'hashes on the page match the files being served.'
